version: 0.0.1-{build}-{branch}
skip_tags: true
image: Visual Studio 2017
platform: x86

pull_requests:
        do_not_increment_build_number: true

install:
        - git submodule update --init --recursive

configuration:
        - Debug
        - Release

build:
        project: SimGLDx11.sln
        verbosity: detailed
